acceso/urls.py
from django.urls import path
from .views import *

urlpatterns =[
    path('login/', acceso_login, name="acceso_login"),
    path('salir', acceso_salir, name="acceso_salir"),
]

bestoff/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from .views import *
from .sitemaps import *

sitemaps = {
    'propiedades': PropiedadesSitemap, # El key de este diccionario puede ser cualquier nombre
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('propiedades/', include('propiedades.urls'), name="propiedades_individuales"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('vender/', vender, name='vender'),
    path('quehacemos/', quehacemos, name='quehacemos'),
    path('acceso/', include('acceso.urls'), name='acceso_urls'),
    path('sse/propiedad/<int:propiedad_id>/', cuentaregresiva, name='cuentaregresiva'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bestoff/forms.py
from django import forms
from django.core import validators
from django.forms import PasswordInput

class formulario_buscar(forms.Form):
	contrato_vigente = forms.BooleanField(required=True, )
	comuna=forms.CharField(required=True,
		widget=forms.TextInput(attrs={'class':'col-span-12 md:col-span-7 mr-1 my-2 rounded-md bg-gray-50 border border-gray-300 text-gray-900 text-sm sm:text-base focus:ring-orange-500 focus:border-orange-500 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-orange-500 dark:focus:border-orange-500','id':'Comuna', 'placeholder':'Ingresa la Comuna...'}))


class formulario_contacto(forms.Form):
    clase='block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-gray-700 focus:outline-none'
    nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Nombre Apellido', 'autocomplete':'off'}))
    email = forms.EmailField(required=False, 
		widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': 'ejemplo@correo.com', 'autocomplete':'off'}
			),
			validators=[
				validators.MinLengthValidator(4, message="El E-Mail es demasiado corto"),
				validators.RegexValidator('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', message="El E-Mail ingresado no es válido")
			],
			error_messages={'required':'El campo E-Mail está vacío' }
		)
    telefono = forms.CharField(required=True, widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': '+56912345678', 'autocomplete':'off'}
			),
			validators=[
                validators.MinLengthValidator(6, message="El Teléfono es demasiado corto"),
                validators.RegexValidator('^[+0-9 ]*$', message="El Teléfono contiene caracteres inválidos, por favor use sólo números, por ejemplo +5691652132")
            ]
	)
    mensaje = forms.CharField(required=True, widget=forms.Textarea(attrs={'class':clase, 'placeholder':'¿Qué quieres vender?', 'style': 'height: 140px', 'autocomplete':'off'}))

class formulario_vender(forms.Form):
	clase=" text-black placeholder-gray-600 w-full px-4 py-2.5 mt-2 text-base   transition duration-500 ease-in-out transform border-transparent rounded-lg bg-gray-200  focus:border-blueGray-500 focus:bg-white dark:focus:bg-gray-800 focus:outline-none focus:shadow-outline focus:ring-2 ring-offset-current ring-offset-2 ring-gray-400"
	nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Nombre Apellido', 'autocomplete':'off'}))
	email = forms.EmailField(required=False, 
		widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': 'ejemplo@correo.com', 'autocomplete':'off'}
			),
			validators=[
				validators.MinLengthValidator(4, message="El E-Mail es demasiado corto"),
				validators.RegexValidator('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', message="El E-Mail ingresado no es válido")
			],
			error_messages={'required':'El campo E-Mail está vacío' }
	)
	telefono = forms.CharField(required=True, 
		widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': '+56912345678', 'autocomplete':'off'}
			),
			validators=[
                validators.MinLengthValidator(6, message="El Teléfono es demasiado corto"),
                validators.RegexValidator('^[+0-9 ]*$', message="El Teléfono contiene caracteres inválidos, por favor use sólo números, por ejemplo +5691652132")
            ]
	)
	comuna=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Comuna', 'autocomplete':'off'}))
	direccion=forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Dirección', 'autocomplete':'off'}))
	caracteristicas=forms.CharField(required=True, widget=forms.Textarea(attrs={'class':clase, 'placeholder':'¿Qué quieres vender?', 'style': 'height: 140px', 'autocomplete':'off'}))


class formulario_contacto_oferta(forms.Form):
	clase='block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-orange-600 focus:outline-none'
	monto = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Monto de la Oferta en UF', 'autocomplete':'off'}))
	nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Nombre Apellido', 'autocomplete':'off'}))
	email = forms.EmailField(required=True, 
		widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': 'ejemplo@correo.com', 'autocomplete':'off'}
			),
			validators=[
				validators.MinLengthValidator(4, message="El E-Mail es demasiado corto"),
				validators.RegexValidator('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', message="El E-Mail ingresado no es válido")
			],
			error_messages={'required':'El campo E-Mail está vacío' }
		)
	telefono = forms.CharField(required=True, widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': '+56912345678', 'autocomplete':'off'}
			),
			validators=[
                validators.MinLengthValidator(4, message="El Teléfono es demasiado corto"),
                validators.RegexValidator('^[+0-9 ]*$', message="El Teléfono contiene caracteres inválidos, por favor use sólo números, por ejemplo +5691652132")
            ]
	)
	forma_pago = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Forma de Pago (ej: crédito hipotecario)',  'autocomplete':'off'}))

class formulario_contacto_oferta_2(forms.Form):
	clase=" text-black placeholder-gray-600 w-full px-4 py-2.5 mt-2 text-base   transition duration-500 ease-in-out transform border-transparent rounded-lg bg-gray-200  focus:border-blueGray-500 focus:bg-white dark:focus:bg-gray-800 focus:outline-none focus:shadow-outline focus:ring-2 ring-offset-current ring-offset-2 ring-gray-400"
	monto = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Monto de la Oferta en UF', 'autocomplete':'off'}))
	nombre = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Nombre Apellido', 'autocomplete':'off'}))
	email = forms.EmailField(required=True, 
		widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': 'ejemplo@correo.com', 'autocomplete':'off'}
			),
			validators=[
				validators.MinLengthValidator(4, message="El E-Mail es demasiado corto"),
				validators.RegexValidator('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+[.]\w{2,3}$', message="El E-Mail ingresado no es válido")
			],
			error_messages={'required':'El campo E-Mail está vacío' }
		)
	telefono = forms.CharField(required=True, widget=forms.TextInput(
			attrs={'class': clase, 'placeholder': '+56912345678', 'autocomplete':'off'}
			),
			validators=[
                validators.MinLengthValidator(4, message="El Teléfono es demasiado corto"),
                validators.RegexValidator('^[+0-9 ]*$', message="El Teléfono contiene caracteres inválidos, por favor use sólo números, por ejemplo +5691652132")
            ]
	)
	forma_pago = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'placeholder':'Forma de Pago (ej: crédito hipotecario)',  'autocomplete':'off'}))

class formulario_financiero(forms.Form):
	#clase='block w-full px-3 py-0.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-orange-600 focus:outline-none'
	clase=" text-black placeholder-gray-600 w-full px-4 py-0.5 mt-2 text-base transition duration-500 ease-in-out transform border-transparent rounded-lg bg-gray-200  focus:border-blueGray-500 focus:bg-white dark:focus:bg-gray-800 focus:outline-none focus:shadow-outline focus:ring-2 ring-offset-current ring-offset-2 ring-gray-400"
	precio_compra = forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class':clase, 'autocomplete':'off'}))
	pie=forms.IntegerField(required=True, widget=forms.TextInput(attrs={'class':clase, 'autocomplete':'off'}))
	tasa= forms.CharField(required=True, widget=forms.TextInput(attrs={'class':clase, 'autocomplete':'off'}))
	arriendo_esperado=forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class':clase, 'autocomplete':'off'}))
	

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}{% load utilidades %}
{% block extra_head %}<title>BESTOFF - Oportunidades Inmobiliarias para todos.</title> 
{% endblock extra_head %}
{% block extra_navbar %} {% include 'componentes/navbar.html' %} {% endblock extra_navbar %}
{% block content %}


<!--Formulario d Búsqueda-->
<div class='busqueda max-w-3xl mx-auto rounded-xl px-5 py-4 bg-red-800/60 mt-7'>
  <div class="text-white">
    <h3 class='text-xl sm:text-3xl'>Busca Inversiones Inmobiliarias como nunca antes lo habías hecho.</h3>
  </div>
    <!--Formulario de Búsqueda Alternativo-->
    <div>
      <form name="form_buscar" method="post" action="{{ request.get_full_path }} ">
        {% csrf_token %}
        <div class="grid grid-cols-12 mt-5">
          {{formulario_buscar.comuna}}
          {{formulario_buscar.contrato_vigente}} <label for="id_contrato_vigente" class="col-span-12 md:col-span-4 rounded-md my-2 p-2.5">&nbsp&nbspContrato Arriendo Vigente</label>
          <button type="button" onclick="buscador();" id="boton-busqueda-portada" class=" boton-busqueda-portada col-span-12 md:col-span-1 ml-1 my-2 flex top-0 right-0 p-2.5 text-sm sm:text-base font-medium text-white rounded-md border border-orange-700">
            <span class="pl-1">Buscar</span>
          </button>
        </div>
      </form>
    </div>
</div>

<!--Ordenar por--><!--
<div class="flex my-4 max-w-3xl mx-2 sm:mx-auto">
  <h2 class="text-sm font-medium title-font mb-4 text-gray-900">Ordenar por:   </h2>
  <a href='propiedades/buscador/?buscar=&&contrato=false&&rentabilidad=true&&plusvalia=false'>
    <div id='mejor_rentabilidad' class="flex">
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 17.25L12 21m0 0l-3.75-3.75M12 21V3" />
        </svg>      
      </span>
      <span class="text-sm text-red-400 font-bold">Mejor Rentabilidad</span>
    </div>
  </a>
  <a href='propiedades/buscador/?buscar=&&contrato=false&&rentabilidad=false&&plusvalia=true'>
    <div id='mejor_plusvalia' class="flex">
    
        <span>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 17.25L12 21m0 0l-3.75-3.75M12 21V3" />
        </svg>      
      </span>
      <span class="text-sm text-red-400 font-bold">Mejor Plusvalia</span>
    </div>
  </a>
</div>-->


<!-- GRid de REsultados con Propiedades Diccionario -->
<div class="grid gap-2 grid-cols-1 sm:grid-cols-3 my-4 max-w-4xl mx-2 sm:mx-auto">
  {% for key, value in propiedades_diccionario.items %}
  <a href="../detalles/0/{{key}}/{{value|accede_diccionario:'comuna'}}-{{propiedad.direccion.split|join:"-"}}" class="c-card block bg-white shadow-md hover:shadow-xl rounded-lg overflow-hidden">  
    <div class="static rounded-2xl">
        <div class="relative pb-1 overflow-hidden rounded-t-lg">
          <div id="z-10 controls-carousel" class="relative" data-carousel="static">
              <!-- Carousel wrapper -->
              <div class="relative h-50 overflow-hidden">
                {% for image in images  %}
                  {% if image.id_propiedades.id == key %}
                    {% if image.default == True %}
                      <div class="relative">
                        <img src="{{ image.image.url }}" class="" alt="...">
                        {% if value|accede_diccionario:'rentabilidad' > 0 %}
                          <div class="flex absolute min-w-full bg-black bottom-3 left-1/2 -translate-x-1/2 bg-opacity-50">
                            <svg class="mx-2" height="18" width="18">
                              <circle cx="9" cy="9" r="5" stroke="green" stroke-width="0" fill="green" />
                            </svg>  
                            <p class="text-xs mr-2 font-bold text-white">ARRIENDO VIGENTE</p>
                          </div>
                      {% endif %}
                      {% if value|accede_diccionario:'propiedad_bancaria' == True %}
                      <div class="flex absolute min-w-full bg-black bottom-3 left-1/2 -translate-x-1/2 bg-opacity-50">
                        <svg class="mx-2" height="18" width="18">
                          <circle cx="9" cy="9" r="5" stroke="green" stroke-width="0" fill="green" />
                        </svg>  
                        <p class="text-xs mr-2 font-bold text-white">PROP-BANCARIA</p>
                      </div>
                      {% endif %}
                      </div>
                    {% endif %}
                  {% endif %}
                {% endfor %}
            </div>
          </div>
        </div>
        <!--Los IF de los -->
        {% if value|accede_diccionario:'rentabilidad' > 0 %}
        <div class="">
          <div class="flex py-1 detalle-rentabilidad  rounded-md border-solid border-slate-100 min-w-sm gallery-item-detalle">
            <svg class="mx-4" height="18" width="18">
              <circle cx="9" cy="9" r="5" stroke="green" stroke-width="0" fill="green" />
            </svg>  
            <p class="text-sm">UF + {{value|accede_diccionario:'rentabilidad'}} % Rent. Anual</p>
          </div>
        </div>
        {% endif %}

        {% if value|accede_diccionario:'plusvalia' > 0 %}
        <div class="">
          <div class="flex py-1 detalle-rentabilidad  rounded-md border-solid border-slate-100 min-w-sm gallery-item-detalle">
            <svg class="mx-4" height="18" width="18">
              <circle cx="9" cy="9" r="5" stroke="green" stroke-width="0" fill="green" />
            </svg> 
            <p class="text-sm">{{value|accede_diccionario:'plusvalia'}} % de plusvalía inmediata</p>
          </div>
        </div>
        {% endif %}      
        <div class="py-1 px-4">
          <h3 class="mt-0 mb-2 text-2xl font-bold">{{value|accede_diccionario:'comuna'}}</h2>
        </div>
        <div id="app" class="py-1 px-4">{{tiempo}}</div>
        <div class="p-2 border-t border-b text-xs text-gray-700">
          <div class="flex justify-between">
                <div> <span class="text-sm font-semibold">UF </span>&nbsp;<span class="font-bold text-3xl">{{value|accede_diccionario:'precio'|numberFormat}}</span></div>
                <button type="submit" class="text-white right-2 bottom-2 bg-orange-700 hover:bg-orange-800 focus:ring-4 focus:outline-none focus:ring-orange-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-orange-600 dark:hover:bg-orange-700 dark:focus:ring-orange-800">Me interesa</button>
          </div>       
        </div>
      </div>
    </a>
  {% endfor %}
</div>


{% endblock content %}
{% block extra_footer %} {% endblock extra_footer %}
{% block scripts %}
<script type="text/javascript">
	function sendSocket()
	{
	var socket=new WebSocket('ws://127.0.0.1:8000/ws/some_url/');
		socket.onmessage=function(event){
			var data=JSON.parse(event.data);
			console.log(data);	
			document.querySelector('#app').innerHTML=data.message;		
		}
		}
		window.onload=function(){
			setInterval(function(){ sendSocket(); }, 1000);

		};
	</script>


{% endblock scripts %}

templates/pages/que_hacemos.html
{% extends 'base.html' %}
{% load static %}{% load utilidades %}
{% block extra_head %}<title>BESTOFF - Oportunidades Inmobiliarias para todos.</title>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v3.10.1/dist/alpine.min.js" defer></script>

{% endblock extra_head %}
{% block extra_navbar %} {% include 'componentes/navbar.html' %} {% endblock extra_navbar %}
{% block content %}

<!-- Container for demo purpose -->
<div class="container my-24 px-6 mx-auto">
  
    <!-- Section: Design Block -->
    <section class="mb-32 text-gray-800">
      <h1 class="text-3xl font-bold mb-12 text-center">¿Qué es Bestoff?</h1>
      <p class="text-gray-900 font-bold mb-12">
        En muy pocas palabras definimos Bestoff como una plataforma transaccional de subastas 
        permanentes para comprar oportunidad inmobiliarias
      </p>  


      <div class="grid lg:grid-cols-3 gap-6">
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Qué es una "plataforma transaccional"?</summary>
          <p class="text-gray-500">
            Una plataforma transaccional es una aplicación web por la cual puedes comprar o vender. Los portales 
            inmobiliarios a los que estamos acostumbrados en Latinoamérica no son transaccionales, porque no puedes
            hacer una oferta o comprar directamente una propiedad. Para comprar un inmueble debes llamar a alguien,
            el dueño o un intermediario, para que, de toda la información necesaria, para luego hacer una oferta y 
            empezar la negociación.</p>
            <p class="text-gray-500">En Bestoff te saltas ese paso tan tedioso. Ponemos a tu disposición todos los antecedentes que necesitas 
            para tomar una decisión informada y hagas la mejor oferta.</p>
        </details>
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Qué son las subastas permanetes?</summary>
          <p class="text-gray-500">
            Las subastas permanentes son remates sin tiempo definido de cierre. Es decir, puedes hacer una oferta en 
            cualquier momento, hasta que el vendedor decida aceptar una.
          </p>
        </details>
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Puedo ofertar menos que el precio de Venta?</summary>
          <p class="text-gray-500">
            Si se puede ofertar menos que el precio en que se anuncia la venta. En Bestoff recomendamos no 
            ofertar menos que el 95% del precio de venta porque la probabilidad de ser aceptada es muy baja.
          </p>
        </details>
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Quién puede hacer una oferta?</summary>
          <p class="text-gray-500">
            Por ahora, dejamos abierta la opción para que cualquiera pueda hacer una oferta. Sin embaro, cada vez que 
            hagas una oferta te contactaremos por teléfono para confirmar la seriedad de esta antes de 
            comunicarsela al vendedor.
          </p>
        </details>
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Qué es una "propiedad bancaria"?</summary>
          <p class="text-gray-500">
            Una propiedad bancaria es un inmueble cuyo dueño es un banco. Generalmente vienen de créditos hipotecarios impagos. Estas propiedades ya fueron rematas y compradas por el banco y, por lo tanto, se venden sin hipotecas ni gravámenes de ningún tipo.
          </p>
        </details>
        <details class="col-md-12 mb-12">
          <summary class="font-bold mb-4">¿Cómo es el proceso para desocupar una propiedad ocupada?</summary>
          <p class="text-gray-500">
            Por lo general, las propiedades bancarias vienen ocupadas por sus antiguos dueños y los bancos vendedores no tienen contactos con ellos. Esto hace que el comprador tenga claro cuáles son los mecanismos para desocupar estas propiedades. Los más comunes son: </p>
            <p class="text-gray-500">1) iniciar un juicio precario contra el ocupante, que tiene un costo aproximado de 35 UF y un plazo de 8 meses. </p>
            <p class="text-gray-500">2) tomar contacto con el ocupante y ofrecerle dinero a cambio de la desocupación. Lo que puede ser más sencillo, barato y rápido que un juicio. Generalmente se negocian hasta 5 meses de arriendo de la propiedad a cambio de la desocupación.</p>
        </details>
      </div>
    </section>
    <!-- Section: Design Block -->
  
</div>
<!-- Container for demo purpose --> 

{% endblock content %}
{% block extra_footer %} {% endblock extra_footer %}
{% block scripts %}<script src="https://unpkg.com/flowbite@1.4.0/dist/flowbite.js"></script>

{% endblock scripts%}